#include "ast/syntax/syntax_ostream_writer.h"
#include "context_manager.h"
#include "doctest.h"

using namespace kisyshot;
using namespace kisyshot::ast;
using namespace kisyshot::diagnostic;


TEST_CASE("lex_test_expected_errors") {
    auto sm = std::make_shared<kisyshot::ContextManager>();
    sm->load("cases/lex/octal_overflow.sy");
    sm->load("cases/lex/comment_not_close.sy");
    sm->lex(0);
    sm->lex(1);
    std::cout << *(sm->diagnosticStream);
    REQUIRE(sm->diagnosticStream->diagnostics.size() == 3);
}

TEST_CASE("lex_test_expected_full_success") {
    auto sm = std::make_shared<kisyshot::ContextManager>();
    sm->load("cases/lex/full_lex.sy");
    sm->lex(0);
// generated by clang-12 -fsyntax-only -Xclang -dump-tokens and modified
    std::vector<kisyshot::ast::TokenType> reference{
            TokenType::kw_const, TokenType::identifier, TokenType::identifier, TokenType::op_eq,
            TokenType::numeric_literal, TokenType::semi, TokenType::identifier, TokenType::identifier,
            TokenType::l_paren, TokenType::identifier, TokenType::identifier, TokenType::comma, TokenType::identifier,
            TokenType::identifier, TokenType::l_square, TokenType::r_square, TokenType::r_paren, TokenType::l_brace,
            TokenType::identifier, TokenType::identifier, TokenType::op_eq, TokenType::numeric_literal,
            TokenType::semi, TokenType::identifier, TokenType::identifier, TokenType::op_eq,
            TokenType::numeric_literal, TokenType::semi, TokenType::kw_while, TokenType::l_paren,
            TokenType::identifier, TokenType::op_less, TokenType::identifier, TokenType::r_paren, TokenType::l_brace,
            TokenType::kw_if, TokenType::l_paren, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_greater, TokenType::identifier, TokenType::r_paren,
            TokenType::identifier, TokenType::op_eq, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::semi, TokenType::identifier, TokenType::op_eq, TokenType::identifier,
            TokenType::op_plus, TokenType::numeric_literal, TokenType::semi, TokenType::r_brace, TokenType::kw_return,
            TokenType::identifier, TokenType::semi, TokenType::r_brace, TokenType::identifier, TokenType::identifier,
            TokenType::l_paren, TokenType::identifier, TokenType::identifier, TokenType::comma, TokenType::identifier,
            TokenType::identifier, TokenType::r_paren, TokenType::l_brace, TokenType::identifier,
            TokenType::identifier, TokenType::op_eq, TokenType::numeric_literal, TokenType::semi,
            TokenType::identifier, TokenType::identifier, TokenType::op_eq, TokenType::numeric_literal,
            TokenType::semi, TokenType::kw_while, TokenType::l_paren, TokenType::identifier, TokenType::op_less,
            TokenType::identifier, TokenType::r_paren, TokenType::l_brace, TokenType::identifier, TokenType::op_eq,
            TokenType::identifier, TokenType::op_slash, TokenType::identifier, TokenType::semi, TokenType::identifier,
            TokenType::op_eq, TokenType::identifier, TokenType::op_plus, TokenType::numeric_literal, TokenType::semi,
            TokenType::r_brace, TokenType::kw_return, TokenType::identifier, TokenType::op_modulus,
            TokenType::identifier,
            TokenType::semi, TokenType::r_brace, TokenType::identifier, TokenType::identifier, TokenType::l_paren,
            TokenType::identifier, TokenType::identifier, TokenType::comma, TokenType::identifier,
            TokenType::identifier, TokenType::l_square, TokenType::r_square, TokenType::comma, TokenType::identifier,
            TokenType::identifier, TokenType::comma, TokenType::identifier, TokenType::identifier, TokenType::r_paren,
            TokenType::l_brace, TokenType::identifier, TokenType::identifier, TokenType::l_square,
            TokenType::identifier, TokenType::r_square, TokenType::op_eq, TokenType::l_brace, TokenType::r_brace,
            TokenType::semi, TokenType::identifier, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_eq, TokenType::l_brace, TokenType::r_brace, TokenType::semi,
            TokenType::identifier, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_eq, TokenType::l_brace, TokenType::r_brace, TokenType::semi,
            TokenType::kw_if, TokenType::l_paren, TokenType::identifier, TokenType::op_equaleq, TokenType::op_minus,
            TokenType::numeric_literal, TokenType::op_pipepipe, TokenType::identifier, TokenType::op_plus,
            TokenType::numeric_literal, TokenType::op_greatereq, TokenType::identifier, TokenType::r_paren,
            TokenType::kw_return, TokenType::semi, TokenType::l_brace, TokenType::identifier, TokenType::identifier,
            TokenType::op_eq, TokenType::identifier, TokenType::semi, TokenType::kw_while, TokenType::l_paren,
            TokenType::identifier, TokenType::op_less, TokenType::identifier, TokenType::r_paren, TokenType::l_brace,
            TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::l_paren,
            TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::r_square, TokenType::comma,
            TokenType::identifier, TokenType::r_paren, TokenType::r_square, TokenType::op_eq, TokenType::identifier,
            TokenType::l_square, TokenType::identifier, TokenType::l_paren, TokenType::identifier, TokenType::l_square,
            TokenType::identifier, TokenType::r_square, TokenType::comma, TokenType::identifier, TokenType::r_paren,
            TokenType::r_square, TokenType::op_plus, TokenType::numeric_literal, TokenType::semi,
            TokenType::identifier, TokenType::op_eq, TokenType::identifier, TokenType::op_plus,
            TokenType::numeric_literal, TokenType::semi, TokenType::r_brace, TokenType::identifier,
            TokenType::l_square, TokenType::numeric_literal, TokenType::r_square, TokenType::op_eq,
            TokenType::identifier, TokenType::semi, TokenType::identifier, TokenType::l_square,
            TokenType::numeric_literal, TokenType::r_square, TokenType::op_eq, TokenType::identifier,
            TokenType::op_plus, TokenType::identifier, TokenType::l_square, TokenType::numeric_literal,
            TokenType::r_square, TokenType::semi, TokenType::identifier, TokenType::op_eq, TokenType::numeric_literal,
            TokenType::semi, TokenType::kw_while, TokenType::l_paren, TokenType::identifier, TokenType::op_less,
            TokenType::identifier, TokenType::r_paren, TokenType::l_brace, TokenType::identifier, TokenType::l_square,
            TokenType::identifier, TokenType::r_square, TokenType::op_eq, TokenType::identifier, TokenType::l_square,
            TokenType::identifier, TokenType::op_minus, TokenType::numeric_literal, TokenType::r_square,
            TokenType::semi,
            TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::r_square, TokenType::op_eq,
            TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::r_square, TokenType::op_plus,
            TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::r_square, TokenType::semi,
            TokenType::identifier, TokenType::op_eq, TokenType::identifier, TokenType::op_plus,
            TokenType::numeric_literal, TokenType::semi, TokenType::r_brace, TokenType::identifier, TokenType::op_eq,
            TokenType::numeric_literal, TokenType::semi, TokenType::kw_while, TokenType::l_paren,
            TokenType::identifier, TokenType::op_less, TokenType::identifier, TokenType::r_paren, TokenType::l_brace,
            TokenType::kw_while, TokenType::l_paren, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_less, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::r_paren, TokenType::l_brace, TokenType::identifier, TokenType::identifier,
            TokenType::op_eq, TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::l_square,
            TokenType::identifier, TokenType::r_square, TokenType::r_square, TokenType::semi, TokenType::kw_while,
            TokenType::l_paren, TokenType::identifier, TokenType::l_paren, TokenType::identifier, TokenType::comma,
            TokenType::identifier, TokenType::r_paren, TokenType::op_exclaimeq, TokenType::identifier,
            TokenType::r_paren, TokenType::l_brace, TokenType::identifier, TokenType::identifier, TokenType::op_eq,
            TokenType::identifier, TokenType::semi, TokenType::identifier, TokenType::op_eq, TokenType::identifier,
            TokenType::l_square, TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::l_paren,
            TokenType::identifier, TokenType::comma, TokenType::identifier, TokenType::r_paren, TokenType::r_square,
            TokenType::r_square, TokenType::semi, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::l_square, TokenType::identifier, TokenType::l_paren, TokenType::identifier, TokenType::comma,
            TokenType::identifier, TokenType::r_paren, TokenType::r_square, TokenType::r_square, TokenType::op_eq,
            TokenType::identifier, TokenType::semi, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::l_paren, TokenType::identifier, TokenType::comma, TokenType::identifier, TokenType::r_paren,
            TokenType::r_square, TokenType::op_eq, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::l_paren, TokenType::identifier, TokenType::comma, TokenType::identifier, TokenType::r_paren,
            TokenType::r_square, TokenType::op_plus, TokenType::numeric_literal, TokenType::semi, TokenType::r_brace,
            TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::l_square,
            TokenType::identifier, TokenType::r_square, TokenType::r_square, TokenType::op_eq, TokenType::identifier,
            TokenType::semi, TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::r_square,
            TokenType::op_eq, TokenType::identifier, TokenType::l_square, TokenType::identifier, TokenType::r_square,
            TokenType::op_plus, TokenType::numeric_literal, TokenType::semi, TokenType::r_brace, TokenType::identifier,
            TokenType::op_eq, TokenType::identifier, TokenType::op_plus, TokenType::numeric_literal, TokenType::semi,
            TokenType::r_brace, TokenType::r_brace, TokenType::l_brace, TokenType::identifier, TokenType::identifier,
            TokenType::op_eq, TokenType::identifier, TokenType::semi, TokenType::identifier, TokenType::l_square,
            TokenType::numeric_literal, TokenType::r_square, TokenType::op_eq, TokenType::identifier, TokenType::semi,
            TokenType::identifier, TokenType::l_square, TokenType::numeric_literal, TokenType::r_square,
            TokenType::op_eq, TokenType::identifier, TokenType::op_plus, TokenType::identifier, TokenType::l_square,
            TokenType::numeric_literal, TokenType::r_square, TokenType::semi, TokenType::identifier, TokenType::op_eq,
            TokenType::numeric_literal, TokenType::semi, TokenType::kw_while, TokenType::l_paren,
            TokenType::identifier, TokenType::op_less, TokenType::identifier, TokenType::r_paren, TokenType::l_brace,
            TokenType::kw_if, TokenType::l_paren, TokenType::identifier, TokenType::op_greater,
            TokenType::numeric_literal, TokenType::r_paren, TokenType::l_brace, TokenType::identifier,
            TokenType::l_square, TokenType::identifier, TokenType::r_square, TokenType::op_eq, TokenType::identifier,
            TokenType::l_square, TokenType::identifier, TokenType::op_minus, TokenType::numeric_literal,
            TokenType::r_square, TokenType::semi, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_eq, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_plus, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::semi, TokenType::r_brace, TokenType::identifier, TokenType::l_paren,
            TokenType::identifier, TokenType::op_minus, TokenType::numeric_literal, TokenType::comma,
            TokenType::identifier, TokenType::comma, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::comma, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::r_paren, TokenType::semi, TokenType::identifier, TokenType::op_eq,
            TokenType::identifier, TokenType::op_plus, TokenType::numeric_literal, TokenType::semi, TokenType::r_brace,
            TokenType::r_brace, TokenType::kw_return, TokenType::semi, TokenType::r_brace, TokenType::identifier,
            TokenType::identifier, TokenType::l_square, TokenType::numeric_literal, TokenType::r_square,
            TokenType::semi, TokenType::identifier, TokenType::identifier, TokenType::semi, TokenType::identifier,
            TokenType::identifier, TokenType::l_paren, TokenType::r_paren, TokenType::l_brace, TokenType::identifier,
            TokenType::identifier, TokenType::op_eq, TokenType::identifier, TokenType::l_paren, TokenType::identifier,
            TokenType::r_paren, TokenType::semi, TokenType::identifier, TokenType::l_paren, TokenType::r_paren,
            TokenType::semi, TokenType::identifier, TokenType::l_paren, TokenType::numeric_literal, TokenType::comma,
            TokenType::identifier, TokenType::comma, TokenType::numeric_literal, TokenType::comma,
            TokenType::identifier, TokenType::r_paren, TokenType::semi, TokenType::identifier, TokenType::identifier,
            TokenType::op_eq, TokenType::numeric_literal, TokenType::semi, TokenType::kw_while, TokenType::l_paren,
            TokenType::identifier, TokenType::op_less, TokenType::identifier, TokenType::r_paren, TokenType::l_brace,
            TokenType::identifier, TokenType::op_eq, TokenType::identifier, TokenType::op_plus, TokenType::identifier,
            TokenType::op_multi, TokenType::l_paren, TokenType::identifier, TokenType::l_square, TokenType::identifier,
            TokenType::r_square, TokenType::op_modulus, TokenType::l_paren, TokenType::numeric_literal,
            TokenType::op_plus, TokenType::identifier, TokenType::r_paren, TokenType::r_paren, TokenType::semi,
            TokenType::identifier, TokenType::op_eq, TokenType::identifier, TokenType::op_plus,
            TokenType::numeric_literal, TokenType::semi, TokenType::r_brace, TokenType::kw_if, TokenType::l_paren,
            TokenType::identifier, TokenType::op_less, TokenType::numeric_literal, TokenType::r_paren,
            TokenType::identifier, TokenType::op_eq, TokenType::op_minus, TokenType::identifier, TokenType::semi,
            TokenType::identifier, TokenType::l_paren, TokenType::r_paren, TokenType::semi, TokenType::identifier,
            TokenType::l_paren, TokenType::identifier, TokenType::r_paren, TokenType::semi, TokenType::identifier,
            TokenType::l_paren, TokenType::numeric_literal, TokenType::r_paren, TokenType::semi, TokenType::kw_return,
            TokenType::numeric_literal, TokenType::semi, TokenType::r_brace, TokenType::eof
    };
    REQUIRE(sm->diagnosticStream->diagnostics.empty());
    auto &tokens = sm->access(0)->tokens;
    REQUIRE(tokens.size() == reference.size());
    for (size_t i = 0; i < tokens.size(); ++i) {
        REQUIRE(tokens[i]->token_type == reference[i]);
    }
}