#pragma once
#include <vector>
#include <string>
#include <string_view>
#include "ast/token.h"
namespace kisyshot{
    class context{
    public:
        /**
         * The path of the given code, used in diagnostics.
         */
        std::string path;
        /**
         * The code reference string.
         */
        std::string_view code;
        /**
         * The reference to the lines of the codes.
         */
        std::vector<std::string_view> lines;
        /**
         * The tokens lexed by Lexer are stored here.
         */
        std::vector<std::unique_ptr<token>> tokens;
        /**
         * The abstract syntax tree generated by parser.
         */
        //std::shared_ptr<syntax::SyntaxUnit> syntaxTree;
    };
}